# Site settings
title: Blogging blog
email: marwes91@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marwes.github.io" # the base hostname & protocol for your site
github_username:  Marwes

# Build settings
markdown: kramdown
